---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: collections-ibm-ms
  name: collections-ibm-ms
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: collections-ibm-ms