---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpd-serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: httpd-sa-rolebinding-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: httpd-serviceaccount