---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloworld
    spec:
      containers:
        - image: docker.io/tarak4u/hello-world:latest
          name: helloworld
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: ""
            - name: IBM_MICROSERVICE_HOST
              value: ""
            - name: IBM_MICROSERVICE_PORT
              value: ""
          resources: {}