---
kind: Secret
apiVersion: v1
metadata:
  name: dockerhub
  namespace: httpd-uat
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJkb2NrZXIuaW8iOiB7CgkJCSJhdXRoIjogImRHRnlZV3MwZFRwS2IzTm9RREV3TVRJeiIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson