kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: driveks-ibm-microservice
  labels:
    app: driveks-ibm-microservice
spec:
  nodeSelector: null
  output:
    to:
      kind: DockerImage
      name: 'nexus-docker-repo.apps.kta-web.ksturnpike.local/ibm-microservice:latest'
    pushSecret:
      name: dockerhub
  resources: {}
  successfulBuildsHistoryLimit: 1
  failedBuildsHistoryLimit: 1
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'git@bitbucket.org:kta/ibm-microservice.git'
    contextDir: /
    sourceSecret:
      name: kta-bitbucket-key
  triggers:
    - type: ConfigChange
    - type: Bitbucket
      bitbucket:
        secretReference:
          name: kta-bitbucket-webhook-secret
  runPolicy: Serial